# Generated by Django 4.2 on 2025-06-09 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0003_job_parsedcompany_alter_jobscore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('size', models.CharField(blank=True, choices=[('startup', 'Startup'), ('small', 'Small (1-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (200+)')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AlterModelOptions(
            name='jobscore',
            options={'ordering': ['-relevance_score', '-updated_at'], 'verbose_name': 'Job Score', 'verbose_name_plural': 'Job Scores'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='jobscore',
            old_name='created_at',
            new_name='calculated_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.RemoveField(
            model_name='jobscore',
            name='score',
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('any', 'Any')], default='any', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_site',
            field=models.CharField(choices=[('cvonline', 'CV Online'), ('cv_ee', 'CV.ee'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='jobscore',
            name='location_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobscore',
            name='relevance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobscore',
            name='salary_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobscore',
            name='skill_match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobscore',
            name='job',
            field=models.OneToOneField(default=3.0, on_delete=django.db.models.deletion.CASCADE, related_name='jobscore', to='scraping.job'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(help_text='Навыки через запятую')),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('location_preference', models.CharField(blank=True, max_length=100)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('is_notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scraping.company'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Интересно'), ('applied', 'Отклик отправлен'), ('interview', 'Интервью'), ('rejected', 'Отказ'), ('accepted', 'Принят')], default='interested', max_length=50)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scraping.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
