# Generated by Django 4.2.7 on 2025-06-09 11:20

import apps.scraping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_company_alter_jobscore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('cvonline', 'CV Online'), ('cv_ee', 'CV.ee'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper',
                'verbose_name_plural': 'Scrapers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='error',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=models.JSONField(default=apps.scraping.models.default_urls),
        ),
    ]
