# Generated by Django 4.2.7 on 2025-06-20 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('job_url', models.URLField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Отклик отправлен'), ('reviewing', 'Рассматривается'), ('interview', 'Собеседование'), ('technical', 'Техническое собеседование'), ('offer', 'Предложение'), ('rejected', 'Отказ'), ('accepted', 'Принят'), ('withdrawn', 'Отозван')], default='applied', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('recruiter_name', models.CharField(blank=True, max_length=100)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.company')),
                ('cv_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.cvversion')),
                ('portfolio_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolioversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Телефонное'), ('video', 'Видео'), ('onsite', 'Личная встреча'), ('technical', 'Техническое'), ('hr', 'HR')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Длительность в минутах')),
                ('interviewer_name', models.CharField(blank=True, max_length=100)),
                ('interviewer_position', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication')),
            ],
        ),
    ]
